<?php
declare(strict_types=1);
require_once __DIR__ . '/auth.php';
requireAdmin();
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>GO COIIN Admin | Applications</title>
<style>
:root{--bg:#06111f;--panel:#0a1b2d;--panel2:#071725;--text:#f7fbff;--muted:#8fa5ba;--blue:#00a8ff;--red:#ff3154;--border:rgba(120,180,220,.16)}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input,select,textarea{font:inherit}
.topbar{position:sticky;top:0;z-index:20;background:rgba(5,16,29,.97);backdrop-filter:blur(14px);border-bottom:1px solid var(--border)}.topbar-in{width:min(1440px,calc(100% - 36px));min-height:74px;margin:auto;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{font-size:24px;font-weight:800;letter-spacing:-.8px}.brand strong{color:var(--red)}.top-actions{display:flex;gap:9px;flex-wrap:wrap}
.btn{display:inline-flex;align-items:center;justify-content:center;min-height:40px;padding:0 14px;border-radius:8px;border:1px solid var(--border);background:#091a2a;color:#fff;text-decoration:none;font-size:12px;font-weight:700;cursor:pointer}.btn.primary{background:linear-gradient(135deg,var(--red),#ff4766);border-color:transparent}.btn.email{background:linear-gradient(135deg,#007ec2,#00a8ff);border-color:transparent}.btn:disabled{opacity:.5;cursor:not-allowed}
.wrap{width:min(1440px,calc(100% - 36px));margin:28px auto 60px}.heading{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:22px}.heading h1{margin:0;font-size:32px;letter-spacing:-1.2px}.heading p{margin:7px 0 0;color:var(--muted);font-size:12px}
.cards{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;margin-bottom:22px}.card{padding:17px;border:1px solid var(--border);border-radius:14px;background:linear-gradient(145deg,var(--panel),var(--panel2))}.card span{display:block;color:var(--muted);font-size:11px}.card strong{display:block;margin-top:8px;font-size:25px}
.toolbar{display:flex;gap:10px;flex-wrap:wrap;padding:14px;border:1px solid var(--border);border-radius:14px;background:#081827;margin-bottom:12px}.toolbar input{flex:1 1 280px;min-height:42px;padding:0 13px;border:1px solid var(--border);border-radius:8px;background:#061421;color:#fff;outline:none}.toolbar select{min-height:42px;padding:0 34px 0 12px;border:1px solid var(--border);border-radius:8px;background:#061421;color:#fff}
.table-shell{overflow:auto;border:1px solid var(--border);border-radius:14px;background:#071725}.table{width:100%;border-collapse:collapse;min-width:1120px}.table th,.table td{padding:13px 12px;text-align:left;border-bottom:1px solid rgba(120,180,220,.08);font-size:11px;vertical-align:top}.table th{color:#8fa5ba;font-size:10px;text-transform:uppercase;letter-spacing:.6px;background:#081a2b;position:sticky;top:0}.name{font-weight:800}.sub{color:#72869a;margin-top:4px}.status{display:inline-flex;padding:5px 8px;border-radius:999px;background:rgba(0,168,255,.08);border:1px solid rgba(0,168,255,.2);color:#8fd3ff;font-weight:800;font-size:10px}.status.rejected{color:#ff9bad;border-color:rgba(255,49,84,.25);background:rgba(255,49,84,.08)}.status.approved{color:#9fe6b5;border-color:rgba(91,210,130,.25);background:rgba(91,210,130,.08)}.status.verified{color:#d6c7ff}.status.contacted{color:#ffe49a}.action-row{display:flex;gap:7px;flex-wrap:wrap}.small-btn{border:1px solid var(--border);background:transparent;color:#8fd3ff;padding:6px 8px;border-radius:7px;font-size:10px;font-weight:800;cursor:pointer}.small-btn.mail{color:#fff;background:rgba(0,168,255,.12)}
.pagination{display:flex;justify-content:space-between;align-items:center;padding:14px 0;color:var(--muted);font-size:11px}.pagination .right{display:flex;gap:8px}
.modal{position:fixed;inset:0;z-index:50;display:none;align-items:center;justify-content:center;padding:18px;background:rgba(0,0,0,.72)}.modal.open{display:flex}.modal-card{width:min(820px,100%);max-height:92vh;overflow:auto;padding:24px;border:1px solid var(--border);border-radius:18px;background:linear-gradient(145deg,#0b2034,#071725);box-shadow:0 30px 100px rgba(0,0,0,.5)}.modal-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.modal-head h2{margin:0;font-size:22px}.close{width:38px;height:38px;border:1px solid var(--border);border-radius:8px;background:#081827;color:#fff;cursor:pointer}.detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:20px}.detail{padding:12px;border:1px solid rgba(120,180,220,.1);border-radius:10px;background:#061421}.detail.full{grid-column:1/-1}.detail label{display:block;color:#71869d;font-size:10px;text-transform:uppercase;letter-spacing:.5px;margin-bottom:6px}.detail div{font-size:13px;line-height:1.6;white-space:pre-wrap;overflow-wrap:anywhere}.edit-row{display:flex;gap:10px;margin-top:18px}.edit-row select,.edit-row textarea,.mail-row input,.mail-row textarea{width:100%;padding:11px;border:1px solid var(--border);border-radius:8px;background:#061421;color:#fff;outline:none}.edit-row textarea{min-height:90px}.edit-row .notes{flex:2}.edit-row .state{flex:1}.section-title{margin:24px 0 10px;font-size:12px;color:#d9e4ef;font-weight:800;letter-spacing:.4px}.mail-box{padding:14px;border:1px solid rgba(0,168,255,.16);border-radius:12px;background:rgba(0,168,255,.04)}.mail-row{display:grid;gap:9px;margin-bottom:10px}.mail-row.two{grid-template-columns:1fr 1fr}.mail-row label{font-size:10px;color:#71869d;text-transform:uppercase;letter-spacing:.5px}.mail-templates{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:10px}.mail-template{border:1px solid var(--border);border-radius:7px;background:#091a2a;color:#a9bfd2;padding:7px 9px;font-size:10px;cursor:pointer}.mail-actions{display:flex;justify-content:flex-end;gap:8px;align-items:center}.hint{color:#71869d;font-size:10px;margin-right:auto}.notice{position:fixed;right:18px;bottom:18px;z-index:100;padding:12px 15px;border:1px solid var(--border);border-radius:10px;background:#0b2034;color:#fff;font-size:12px;display:none}.notice.show{display:block}
@media(max-width:1000px){.cards{grid-template-columns:repeat(3,1fr)}}@media(max-width:620px){.wrap,.topbar-in{width:min(100% - 24px,1440px)}.heading{align-items:flex-start;flex-direction:column}.cards{grid-template-columns:repeat(2,1fr)}.detail-grid,.mail-row.two{grid-template-columns:1fr}.detail.full{grid-column:auto}.top-actions .btn:first-child{display:none}.mail-actions{align-items:stretch;flex-direction:column}.hint{margin:0}}
</style>
</head>
<body>
<header class="topbar"><div class="topbar-in"><div class="brand"><strong>GO</strong> COIIN <span style="font-size:10px;color:#71869d;font-weight:600">ADMIN</span></div><div class="top-actions"><a class="btn primary" href="index.php">Account Openings</a><a class="btn" href="withdrawals.php">Withdrawal Forms</a><a class="btn" href="export.php">Export CSV</a><button class="btn" id="refreshBtn" type="button">Refresh</button><a class="btn" href="change-password.php">Change Password</a><a class="btn" href="logout.php">Logout</a></div></div></header>
<main class="wrap">
<div class="heading"><div><h1>Account Applications</h1><p>Customer enquiries submitted through the GO COIIN website.</p></div></div>
<section class="cards" id="stats"><div class="card"><span>Total</span><strong>—</strong></div><div class="card"><span>New</span><strong>—</strong></div><div class="card"><span>Contacted</span><strong>—</strong></div><div class="card"><span>Verified</span><strong>—</strong></div><div class="card"><span>Approved</span><strong>—</strong></div><div class="card"><span>Rejected</span><strong>—</strong></div></section>
<div class="toolbar"><input id="search" type="search" placeholder="Search name, email, phone, country or application ID..."><select id="status"><option value="">All statuses</option><option>New</option><option>Contacted</option><option>Verified</option><option>Approved</option><option>Rejected</option></select><button class="btn primary" id="searchBtn" type="button">Search</button></div>
<div class="table-shell"><table class="table"><thead><tr><th>Application</th><th>Applicant</th><th>Contact</th><th>Country</th><th>Account</th><th>Status</th><th>Submitted</th><th>Actions</th></tr></thead><tbody id="rows"><tr><td colspan="8" style="padding:40px;text-align:center;color:#8fa5ba">Loading applications…</td></tr></tbody></table></div>
<div class="pagination"><span id="count">—</span><div class="right"><button class="btn" id="prev" type="button">Previous</button><button class="btn" id="next" type="button">Next</button></div></div>
</main>
<div class="modal" id="modal"><div class="modal-card"><div class="modal-head"><div><h2 id="modalTitle">Application</h2><p id="modalSub" style="color:#8fa5ba;font-size:11px;margin:6px 0 0"></p></div><button class="close" id="closeModal" type="button">×</button></div>
<div class="detail-grid" id="details"></div>
<div class="edit-row"><div class="state"><label style="display:block;color:#71869d;font-size:10px;margin:0 0 6px">STATUS</label><select id="editStatus"><option>New</option><option>Contacted</option><option>Verified</option><option>Approved</option><option>Rejected</option></select></div><div class="notes"><label style="display:block;color:#71869d;font-size:10px;margin:0 0 6px">ADMIN NOTES</label><textarea id="editNotes" placeholder="Internal notes..."></textarea></div></div><button class="btn primary" style="margin-top:10px" id="saveBtn" type="button">Save Application</button>
<div class="section-title">EMAIL TRADER — MT5 LOGIN CREDENTIALS</div><div class="mail-box"><div class="mail-row two"><div><label>Client Name</label><input id="credName" type="text" maxlength="200"></div><div><label>Email</label><input id="mailTo" type="email" maxlength="190"></div></div><div class="mail-row two"><div><label>Contact</label><input id="credContact" type="text" maxlength="50"></div><div><label>Login ID</label><input id="credLoginId" type="text" maxlength="100"></div></div><div class="mail-row two"><div><label>Master Password</label><input id="credMasterPassword" type="text" maxlength="120"></div><div><label>Investor Password</label><input id="credInvestorPassword" type="text" maxlength="120"></div></div><div class="mail-row"><label>Subject</label><input id="mailSubject" type="text" maxlength="180" readonly></div><div class="mail-row"><label>Message</label><textarea id="mailMessage" rows="15" maxlength="12000" readonly></textarea></div><div class="mail-actions"><span class="hint">Default GO COIIN credentials email is fixed. You can edit only Name, Email, Contact, Login ID, Master Password and Investor Password.</span><button class="btn email" id="sendEmailBtn" type="button">Send Email</button></div></div>
</div></div>
<div class="notice" id="notice"></div>
<script>
const state={offset:0,limit:50,current:null};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function notice(msg){const n=$('notice');n.textContent=msg;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),2800)}
async function api(url,opts){const r=await fetch(url,opts);const d=await r.json().catch(()=>({ok:false,message:'Invalid server response'}));if(r.status===401){location.href='login.php';throw new Error('Session expired');}if(!r.ok||!d.ok)throw new Error(d.message||'Request failed');return d}
async function loadStats(){const d=await api('api.php?action=stats');const s=d.stats;const vals=[s.total,s.new_count,s.contacted_count,s.verified_count,s.approved_count,s.rejected_count];document.querySelectorAll('#stats strong').forEach((el,i)=>el.textContent=Number(vals[i]||0).toLocaleString())}
async function load(){const search=encodeURIComponent($('search').value.trim());const status=encodeURIComponent($('status').value);const d=await api(`api.php?action=list&limit=${state.limit}&offset=${state.offset}&search=${search}&status=${status}`);const rows=$('rows');if(!d.applications.length){rows.innerHTML='<tr><td colspan="8" style="padding:40px;text-align:center;color:#8fa5ba">No applications found.</td></tr>'}else{rows.innerHTML=d.applications.map(a=>{const full=`${a.first_name} ${a.last_name}`;return `<tr><td><div class="name">${esc(a.application_ref)}</div><div class="sub">${esc(a.created_at)} UTC</div></td><td><div class="name">${esc(full)}</div><div class="sub">${esc(a.account_type)}</div></td><td><div>${esc(a.email)}</div><div class="sub">${esc(a.phone)}</div></td><td>${esc(a.country)}</td><td>${esc(a.account_type)}</td><td><span class="status ${a.status.toLowerCase()}">${esc(a.status)}</span></td><td>${esc(a.created_at)}</td><td><div class="action-row"><button class="small-btn" data-action="view" data-id="${a.id}" type="button">View</button><button class="small-btn mail" data-action="mail" data-id="${a.id}" type="button">Email</button></div></td></tr>`}).join('');document.querySelectorAll('[data-action="view"]').forEach(b=>b.addEventListener('click',()=>openDetails(d.applications.find(a=>String(a.id)===b.dataset.id))));document.querySelectorAll('[data-action="mail"]').forEach(b=>b.addEventListener('click',()=>openDetails(d.applications.find(a=>String(a.id)===b.dataset.id))))}const start=d.total?state.offset+1:0;const end=Math.min(state.offset+d.applications.length,d.total);$('count').textContent=`Showing ${start}–${end} of ${d.total}`;$('prev').disabled=state.offset===0;$('next').disabled=end>=d.total}
function renderCredentialMessage(){const message=`Dear Mr./Ms. ${$('credName').value || '[Client Name]'},\n\nThanks you for choosing GO COIIN as your trading partner.\nBelow you can find your login credentials.\n\nName            : ${$('credName').value || '[Client Name]'}\nEmail           : ${$('mailTo').value || '[Client Email]'}\nContact         : ${$('credContact').value || '[Contact]'}\nLogin ID        : ${$('credLoginId').value || '[Login ID]'}\nMaster Password : ${$('credMasterPassword').value || '[Master Password]'}\nInvestor Password: ${$('credInvestorPassword').value || '[Investor Password]'}\n\n(server name: (stark capital markets))\n\nplease do not hesitate to contact us for any further assistance\n\nWe are sending you the MT5 setup full via whatsapp we\nalso request you to kindly download\n\n\nThanks and Regards\n    GO COIIN\nwww.gocoiin.com`;$('mailMessage').value=message}
function loadCredentialTemplate(){const a=state.current;if(!a)return;$('credName').value=`${a.first_name} ${a.last_name}`;$('mailTo').value=a.email||'';$('credContact').value=a.phone||'';$('credLoginId').value='';$('credMasterPassword').value='';$('credInvestorPassword').value='';$('mailSubject').value='Login Credentials For GO COIIN';renderCredentialMessage()}
function openDetails(a){if(!a)return;state.current=a;$('modalTitle').textContent=`${a.first_name} ${a.last_name}`;$('modalSub').textContent=`${a.application_ref} · Submitted ${a.created_at} UTC`;$('editStatus').value=a.status;$('editNotes').value=a.admin_notes||'';const items=[['Email',a.email],['Phone',a.phone],['Country / Region',a.country],['Preferred Account',a.account_type],['Risk Acknowledgement',a.risk_acknowledged?'Yes':'No'],['Last Updated',`${a.updated_at} UTC`],['Message',a.message||'—'],['Admin Notes',a.admin_notes||'—']];$('details').innerHTML=items.map((x,i)=>`<div class="detail ${i>5?'full':''}"><label>${esc(x[0])}</label><div>${esc(x[1])}</div></div>`).join('');loadCredentialTemplate();$('modal').classList.add('open')}
const templates={credentials:{subject:'Login Credentials For GO COIIN'}};
function applyTemplate(key){if(!state.current||!templates[key])return;const t=templates[key];const name=`${state.current.first_name} ${state.current.last_name}`;$('mailSubject').value=t.subject.replaceAll('{name}',name).replaceAll('{ref}',state.current.application_ref);$('mailMessage').value=t.message.replaceAll('{name}',name).replaceAll('{ref}',state.current.application_ref)}
$('closeModal').onclick=()=>$('modal').classList.remove('open');$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.remove('open')};$('saveBtn').onclick=async()=>{if(!state.current)return;try{await api('api.php',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:state.current.id,status:$('editStatus').value,adminNotes:$('editNotes').value})});state.current.status=$('editStatus').value;state.current.admin_notes=$('editNotes').value;await Promise.all([load(),loadStats()]);notice('Application updated.')}catch(e){notice(e.message)}};
document.querySelectorAll('.mail-template').forEach(b=>b.addEventListener('click',()=>loadCredentialTemplate()));
['credName','mailTo','credContact','credLoginId','credMasterPassword','credInvestorPassword'].forEach(id=>$(id).addEventListener('input',renderCredentialMessage));
$('sendEmailBtn').onclick=async()=>{if(!state.current)return;const subject=$('mailSubject').value.trim();const message=$('mailMessage').value.trim();if(!subject||!message){notice('Enter an email subject and message.');return;}const b=$('sendEmailBtn');b.disabled=true;b.textContent='Sending…';try{const d=await api('send-email.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({applicationId:state.current.id,recipient:$('mailTo').value.trim(),subject,message})});notice(d.message||'Email sent.');}catch(e){notice(e.message)}finally{b.disabled=false;b.textContent='Send Email'}};
$('refreshBtn').onclick=()=>Promise.all([load(),loadStats()]);$('searchBtn').onclick=()=>{state.offset=0;load().catch(e=>notice(e.message))};$('search').addEventListener('keydown',e=>{if(e.key==='Enter')$('searchBtn').click()});$('prev').onclick=()=>{state.offset=Math.max(0,state.offset-state.limit);load().catch(e=>notice(e.message))};$('next').onclick=()=>{state.offset+=state.limit;load().catch(e=>notice(e.message))};
load().catch(e=>notice(e.message));loadStats().catch(e=>notice(e.message));setInterval(()=>{load().catch(()=>{});loadStats().catch(()=>{})},15000);
</script>
</body></html>
